/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TPO6;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TPO6.modelo.Producto;

/**
 *
 * @author Cristian
 */
public class ConsultaPorPrecio extends javax.swing.JInternalFrame {
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ConsultaPorPrecio
     */
    public ConsultaPorPrecio() {
        
        initComponents();
        BorrarFilas();
       
        
       
        String ids [] = {"Codigo" , "Descripcion", "Precio", "Stock","Categoria"};
        modelo.setColumnIdentifiers(ids);
        jTrubro.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTrubro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTmenor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTmayor = new javax.swing.JTextField();

        setClosable(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Precio");

        jTrubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTrubro);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Entre $ :");

        jTmenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmenorActionPerformed(evt);
            }
        });
        jTmenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmenorKeyReleased(evt);
            }
        });

        jLabel3.setText("y");

        jTmayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmayorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jTmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(jTmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTmenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTmayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTmenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmenorActionPerformed
        // TODO add your handling code here:
       
            
    }//GEN-LAST:event_jTmenorActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jTmenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmenorKeyReleased
        // TODO add your handling code here:
         BorrarFilas();
         if(!jTmenor.getText().isEmpty()&& !jTmayor.getText().isEmpty()){
            try{
                int menor=Integer.parseInt(jTmenor.getText());
                int mayor=Integer.parseInt(jTmayor.getText());
                for (Producto nuevo:MenuGeneral.productos){
                    if(menor <= nuevo.getPrecio() && mayor >= nuevo.getPrecio()){
                        modelo.addRow(new Object[]{nuevo.getCodigo(),nuevo.getDescripcion(),nuevo.getPrecio(),nuevo.getStock(),nuevo.getRubro()});
                    }
                }
            }catch (NumberFormatException nf){
                JOptionPane.showMessageDialog(this, "ERROR-Solo ingresar numeros");
            }
        }
    }//GEN-LAST:event_jTmenorKeyReleased

    private void jTmayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmayorKeyReleased
        // TODO add your handling code here:
        BorrarFilas();
         if(!jTmenor.getText().isEmpty()&& !jTmayor.getText().isEmpty()){
            try{
                int menor=Integer.parseInt(jTmenor.getText());
                int mayor=Integer.parseInt(jTmayor.getText());
                for (Producto nuevo:MenuGeneral.productos){
                    if(menor <= nuevo.getPrecio() && mayor >= nuevo.getPrecio()){
                        modelo.addRow(new Object[]{nuevo.getCodigo(),nuevo.getDescripcion(),nuevo.getPrecio(),nuevo.getStock(),nuevo.getRubro()});
                    }
                }
            }catch (NumberFormatException nf){
                JOptionPane.showMessageDialog(this, "ERROR-Solo ingresar numeros");
            }
        }
    }//GEN-LAST:event_jTmayorKeyReleased

private void BorrarFilas(){
    int ind = modelo.getRowCount() -1 ;
    for( int i = ind ; i >= 0 ; i--){
    modelo.removeRow(i);
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTmayor;
    private javax.swing.JTextField jTmenor;
    private javax.swing.JTable jTrubro;
    // End of variables declaration//GEN-END:variables
}
